=== Yuri1965/XMLParser/src/main/resources/Gems.xsd
<?xml version="1.0" encoding="utf-8"?>
<schema xmlns:tns="http://www.epam.education.com/Gems"
        targetNamespace="http://www.epam.education.com/Gems"
        xmlns="http://www.w3.org/2001/XMLSchema">

    <element name="ListGems">
        <complexType>
            <sequence>
                <element minOccurs="1" maxOccurs="unbounded" name="gem" type="tns:Gem" />
            </sequence>
        </complexType>
    </element>

    <complexType name="Gem">
        <sequence>
            <element name="Name" type="string" />
            <element name="Value" type="tns:valueType" />
            <element name="Origin" type="tns:originsType" />
            <element name="Preciousness" type="tns:preciousnessType" />
            <element name="VisualParams" type="tns:visualParamType" />
        </sequence>
        <attribute name="GemID" type="tns:gemID" use="required" />
    </complexType>

    <simpleType name="gemID" >
        <restriction base="ID" />
    </simpleType>

    <complexType name="visualParamType">
        <sequence>
            <element name="colorName" type="tns:colorType" />
            <element name="transparencyValue" type="tns:transparencyType" />
            <element name="quantitySides" type="tns:quantitySideType" />
        </sequence>
    </complexType>

    <simpleType name="quantitySide">
        <restriction base="positiveInteger">
            <minInclusive value="4"/>
            <maxInclusive value="15"/>
        </restriction>
    </simpleType>

    <complexType name="quantitySideType" >
        <simpleContent>
            <extension base="tns:quantitySide">
                <attribute name="quantitySideName" type="string" fixed="side" use="required"/>
            </extension>
        </simpleContent>
    </complexType>

    <simpleType name="transparency">
        <restriction base="positiveInteger">
            <maxInclusive value="100"/>
        </restriction>
    </simpleType>

    <complexType name="transparencyType" >
        <simpleContent>
            <extension base="tns:transparency">
                <attribute name="weightTransparency" type="string" fixed="%" use="required"/>
            </extension>
        </simpleContent>
    </complexType>

    <simpleType name="colorType">
        <restriction base="string">
            <enumeration value="WHITE"/>
            <enumeration value="RED"/>
            <enumeration value="GREEN"/>
            <enumeration value="YELLOW"/>
            <enumeration value="BLUE"/>
        </restriction>
    </simpleType>

    <complexType name="valueType" >
        <simpleContent>
            <extension base="tns:value">
                <attribute name="weightName" type="string" fixed="ct" use="required"/>
            </extension>
        </simpleContent>
    </complexType>

    <simpleType name="value">
        <restriction base="decimal">
            <fractionDigits value="2"/>
            <minInclusive value="0.01"/>
            <maxInclusive value="10000.00"/>
        </restriction>
    </simpleType>

    <simpleType name="continentType">
        <restriction base="string">
            <enumeration value="Afrique"/>
            <enumeration value="Australia"/>
            <enumeration value="Azia"/>
            <enumeration value="Europe"/>
            <enumeration value="North America"/>
            <enumeration value="South America"/>
        </restriction>
    </simpleType>

    <complexType name="originsType">
        <sequence>
            <element name="continent" type="tns:continentType" />
            <element name="country" type="string" />
            <element name="region" type="string" />
        </sequence>
    </complexType>

    <simpleType name="preciousnessType">
        <restriction base="string">
            <enumeration value="Jewel" />
            <enumeration value="NoJewel" />
        </restriction>
    </simpleType>


</schema>

=== Yuri1965/XMLParser/Gems_test4.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<gems:ListGems xmlns:gems="http://www.epam.education.com/Gems" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.epam.education.com/Gems http://www.epam.education.com/Gems/Gems.xsd">
    <gem GemID="a6b74c9e9-2156-4712-b0ea-fd880d2a7260">
        <Name>Rubin</Name>
        <Value weightName="ct">1000.00</Value>
        <Origin>
            <continent>Europe</continent>
            <country>Russia</country>
            <region>Siberia</region>
        </Origin>
        <Preciousness>Jewel</Preciousness>
        <VisualParams>
            <colorName>RED</colorName>
            <transparencyValue weightTransparency="%">90</transparencyValue>
            <quantitySides quantitySideName="side">10</quantitySides>
        </VisualParams>
    </gem>
    <gem GemID="b6b74c9e9-2156-4712-b0ea-fd880d2a7260">
        <Name>Rubin</Name>
        <Value weightName="ct">200.00</Value>
        <Origin>
            <continent>Europe</continent>
            <country>Russia</country>
            <region>Siberia</region>
        </Origin>
        <Preciousness>Jewel</Preciousness>
        <VisualParams>
            <colorName>RED</colorName>
            <transparencyValue weightTransparency="%">100</transparencyValue>
            <quantitySides quantitySideName="side">15</quantitySides>
        </VisualParams>
    </gem>
    <gem GemID="c6b74c9e9-2156-4712-b0ea-fd880d2a7260">
        <Name>Diamond</Name>
        <Value weightName="ct">200.00</Value>
        <Origin>
            <continent>Afrique</continent>
            <country>Nigeria</country>
            <region>Jungle</region>
        </Origin>
        <Preciousness>Jewel</Preciousness>
        <VisualParams>
            <colorName>WHITE</colorName>
            <transparencyValue weightTransparency="%">100</transparencyValue>
            <quantitySides quantitySideName="side">10</quantitySides>
        </VisualParams>
    </gem>
    <gem GemID="d6b74c9e9-2156-4712-b0ea-fd880d2a7260">
        <Name>Emerald</Name>
        <Value weightName="ct">250.00</Value>
        <Origin>
            <continent>Afrique</continent>
            <country>Nigeria</country>
            <region>Jungle</region>
        </Origin>
        <Preciousness>Jewel</Preciousness>
        <VisualParams>
            <colorName>GREEN</colorName>
            <transparencyValue weightTransparency="%">95</transparencyValue>
            <quantitySides quantitySideName="side">12</quantitySides>
        </VisualParams>
    </gem>
    <gem GemID="e6b74c9e9-2156-4712-b0ea-fd880d2a7260">
        <Name>Corundum</Name>
        <Value weightName="ct">1250.00</Value>
        <Origin>
            <continent>Europe</continent>
            <country>Russia</country>
            <region>North Ural</region>
        </Origin>
        <Preciousness>NoJewel</Preciousness>
        <VisualParams>
            <colorName>RED</colorName>
            <transparencyValue weightTransparency="%">85</transparencyValue>
            <quantitySides quantitySideName="side">15</quantitySides>
        </VisualParams>
    </gem>
    <gem GemID="f6b74c9e9-2156-4712-b0ea-fd880d2a7260">
        <Name>Amethyst</Name>
        <Value weightName="ct">5250.00</Value>
        <Origin>
            <continent>Europe</continent>
            <country>Russia</country>
            <region>South Ural</region>
        </Origin>
        <Preciousness>NoJewel</Preciousness>
        <VisualParams>
            <colorName>YELLOW</colorName>
            <transparencyValue weightTransparency="%">85</transparencyValue>
            <quantitySides quantitySideName="side">15</quantitySides>
        </VisualParams>
    </gem>
    <gem GemID="uuid_19e545e1-4477-43bf-a452-7993ac643248">
        <Name>Diamond Blue</Name>
        <Value weightName="ct">1150.5</Value>
        <Origin>
            <continent>Azia</continent>
            <country>China</country>
            <region>Goncong</region>
        </Origin>
        <Preciousness>Jewel</Preciousness>
        <VisualParams>
            <colorName>BLUE</colorName>
            <transparencyValue weightTransparency="%">100</transparencyValue>
            <quantitySides quantitySideName="side">12</quantitySides>
        </VisualParams>
    </gem>
    <gem GemID="uuid_031ac4d5-5552-49bf-92e2-19cf0307cd03">
        <Name>Emerald</Name>
        <Value weightName="ct">250.8</Value>
        <Origin>
            <continent>Australia</continent>
            <country>Australia</country>
            <region>Ceiptawn-sity</region>
        </Origin>
        <Preciousness>Jewel</Preciousness>
        <VisualParams>
            <colorName>GREEN</colorName>
            <transparencyValue weightTransparency="%">98</transparencyValue>
            <quantitySides quantitySideName="side">7</quantitySides>
        </VisualParams>
    </gem>
</gems:ListGems>
